import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#673d00",
        "on-primary-fixed-variant": "#004b74",
        "surface-container-highest": "#e1e2e7",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb869",
        "surface-container-high": "#e6e8ed",
        "surface-container": "#eceef3",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002115",
        "surface-tint": "#006398",
        "outline-variant": "#c0c7d0",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007151",
        "inverse-surface": "#2d3134",
        "secondary-container": "#83f5c6",
        "tertiary": "#774700",
        "on-tertiary-container": "#ffe7d1",
        "surface": "#f8f9fe",
        "inverse-primary": "#93ccff",
        "tertiary-container": "#985c00",
        "on-surface-variant": "#40474f",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2b1700",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f5",
        "background": "#f8f9fe",
        "primary-container": "#1d6fa4",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#68dbae",
        "secondary-fixed": "#86f8c9",
        "tertiary-fixed": "#ffdcbb",
        "primary": "#005684",
        "on-secondary-fixed-variant": "#00513a",
        "surface-container-low": "#f2f3f8",
        "surface-bright": "#f8f9fe",
        "primary-fixed-dim": "#93ccff",
        "surface-variant": "#e1e2e7",
        "on-primary": "#ffffff",
        "secondary": "#006c4e",
        "primary-fixed": "#cde5ff",
        "on-surface": "#191c1f",
        "surface-dim": "#d8dadf",
        "on-background": "#191c1f",
        "outline": "#717880",
        "on-primary-fixed": "#001d31",
        "on-primary-container": "#dcedff",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        chinese: ["Noto Sans SC", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
