"use client";

import { useState, useEffect } from "react";

interface AiQuestion {
  id: string;
  vocabularyId: string;
  questionText: string;
  correctAnswer: string;
  options: string[];
  hskLevel: number;
  type: string;
  explanation: string | null;
  imageUrl: string | null;
  difficulty: string;
  generatedBy: string;
  status: string;
  createdAt: string;
  vocabulary: {
    hanzi: string;
    pinyin: string;
    meaningVi: string;
    hskLevel: number;
  };
}

const STATUS_CONFIG: Record<string, { label: string; cls: string }> = {
  pending:   { label: "Chờ duyệt", cls: "bg-amber-100 text-amber-700" },
  approved:  { label: "Đã duyệt",  cls: "bg-green-100 text-green-700" },
  rejected:  { label: "Từ chối",   cls: "bg-red-100 text-red-700" },
};

const HSK_COLORS = ["", "bg-green-500", "bg-teal-500", "bg-blue-500", "bg-indigo-500", "bg-purple-500", "bg-red-500"];

function Skeleton({ className = "" }: { className?: string }) {
  return <div className={`animate-pulse bg-surface-container rounded-xl ${className}`} />;
}

// ─── Preview Modal ────────────────────────────────────────────────────────────
function QuestionModal({ q, onClose, onAction }: {
  q: AiQuestion;
  onClose: () => void;
  onAction: (id: string, action: "approve" | "reject") => void;
}) {
  const [saving, setSaving] = useState(false);
  const [edit, setEdit] = useState({
    questionText: q.questionText,
    correctAnswer: q.correctAnswer,
    options: Array.isArray(q.options) ? q.options : [],
    explanation: q.explanation ?? "",
    imageUrl: q.imageUrl ?? "",
  });

  const save = async () => {
    setSaving(true);
    await fetch(`/api/admin/ai-questions/${q.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...edit, status: "pending" }),
    });
    setSaving(false);
    onAction(q.id, "approve");
  };

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
      <div className="bg-surface-container-lowest rounded-2xl shadow-2xl w-full max-w-2xl border border-outline-variant/20 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-outline-variant/10 sticky top-0 bg-surface-container-lowest z-10">
          <div className="flex items-center gap-3">
            <div className={`w-2.5 h-2.5 rounded-full ${HSK_COLORS[q.hskLevel] ?? "bg-gray-400"}`} />
            <span className="text-sm font-bold text-on-surface-variant">HSK {q.hskLevel}</span>
            <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${STATUS_CONFIG[q.status]?.cls ?? "bg-gray-100 text-gray-600"}`}>
              {STATUS_CONFIG[q.status]?.label ?? q.status}
            </span>
          </div>
          <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-surface-container">
            <span className="material-symbols-outlined text-on-surface-variant" style={{ fontSize: 20 }}>close</span>
          </button>
        </div>

        <div className="p-6 space-y-4">
          {/* Vocab info */}
          <div className="bg-surface-container rounded-2xl p-4 flex items-center gap-4">
            <div className="text-4xl chinese-text">{q.vocabulary.hanzi}</div>
            <div>
              <div className="text-sm text-on-surface-variant">{q.vocabulary.pinyin}</div>
              <div className="font-semibold text-on-surface">{q.vocabulary.meaningVi}</div>
              <div className="text-xs text-on-surface-variant mt-0.5">Generated by: {q.generatedBy}</div>
            </div>
          </div>

          {/* Image URL */}
          <div>
            <label className="text-xs font-bold text-on-surface-variant uppercase mb-1 block">Hình ảnh minh hoạ</label>
            <input
              value={edit.imageUrl}
              onChange={e => setEdit(p => ({ ...p, imageUrl: e.target.value }))}
              className="w-full border border-outline-variant/30 rounded-xl px-4 py-3 text-sm outline-none focus:border-primary mb-2"
              placeholder="https://..."
            />
            {edit.imageUrl && (
              <img
                src={edit.imageUrl}
                alt="preview"
                className="w-full max-h-40 rounded-xl object-cover border border-outline-variant/20"
                onError={e => { (e.target as HTMLImageElement).style.display = "none"; }}
              />
            )}
          </div>

          {/* Question Text */}
          <div>
            <label className="text-xs font-bold text-on-surface-variant uppercase mb-1 block">Câu hỏi</label>
            <textarea
              value={edit.questionText}
              onChange={e => setEdit(p => ({ ...p, questionText: e.target.value }))}
              rows={2}
              className="w-full border border-outline-variant/30 rounded-xl px-4 py-3 text-sm outline-none focus:border-primary resize-none"
            />
          </div>

          {/* Options */}
          <div>
            <label className="text-xs font-bold text-on-surface-variant uppercase mb-2 block">Đáp án</label>
            <div className="grid grid-cols-1 gap-2">
              {edit.options.map((opt, i) => (
                <div key={i} className={`flex items-center gap-2 border rounded-xl px-3 py-2.5 ${opt === edit.correctAnswer ? "border-green-500 bg-green-50" : "border-outline-variant/30"}`}>
                  <span className="w-6 h-6 bg-surface-container rounded-lg flex items-center justify-center text-xs font-bold text-on-surface-variant flex-shrink-0">
                    {String.fromCharCode(65 + i)}
                  </span>
                  <input
                    value={opt}
                    onChange={e => {
                      const opts = [...edit.options];
                      opts[i] = e.target.value;
                      setEdit(p => ({ ...p, options: opts }));
                    }}
                    className="flex-1 text-sm outline-none bg-transparent"
                  />
                  <button
                    onClick={() => setEdit(p => ({ ...p, correctAnswer: opt }))}
                    className={`text-xs font-bold px-2 py-1 rounded-lg ${opt === edit.correctAnswer ? "bg-green-500 text-white" : "bg-surface-container text-on-surface-variant hover:bg-surface-container-high"}`}
                  >
                    ✓ Đúng
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Explanation */}
          <div>
            <label className="text-xs font-bold text-on-surface-variant uppercase mb-1 block">Giải thích</label>
            <textarea
              value={edit.explanation}
              onChange={e => setEdit(p => ({ ...p, explanation: e.target.value }))}
              rows={2}
              className="w-full border border-outline-variant/30 rounded-xl px-4 py-3 text-sm outline-none focus:border-primary resize-none"
              placeholder="Giải thích ngắn bằng tiếng Việt..."
            />
          </div>
        </div>

        <div className="px-6 py-4 border-t border-outline-variant/10 flex justify-between gap-3">
          <div className="flex gap-2">
            <button onClick={() => { fetch(`/api/admin/ai-questions/${q.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...edit, status: "rejected" }) }); onAction(q.id, "reject"); }}
              className="px-4 py-2 border border-red-200 text-red-600 rounded-xl text-sm font-bold hover:bg-red-50 transition-all">
              Từ chối
            </button>
          </div>
          <div className="flex gap-2">
            <button onClick={onClose}
              className="px-5 py-2 border border-outline-variant/40 rounded-xl text-sm font-bold text-on-surface hover:bg-surface-container">
              Huỷ
            </button>
            <button onClick={save} disabled={saving}
              className="flex items-center gap-2 px-5 py-2 bg-green-600 text-white rounded-xl text-sm font-bold hover:brightness-110 disabled:opacity-50">
              {saving && <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />}
              Lưu & Duyệt
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function AdminAiQuestionsPage() {
  const [questions, setQuestions] = useState<AiQuestion[]>([]);
  const [stats, setStats] = useState<{ status: string; count: number }[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [searchQ, setSearchQ] = useState("");
  const [hskFilter, setHskFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [page, setPage] = useState(1);
  const [preview, setPreview] = useState<AiQuestion | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const fetchQ = async (q = searchQ, hsk = hskFilter, status = statusFilter, p = page) => {
    setLoading(true);
    const params = new URLSearchParams({ q, page: String(p), limit: "20" });
    if (hsk)    params.set("hsk", hsk);
    if (status) params.set("status", status);
    const res = await fetch(`/api/admin/ai-questions?${params}`);
    const data = await res.json();
    setQuestions(data.questions ?? []);
    setStats(data.stats ?? []);
    setTotal(data.pagination?.total ?? 0);
    setLoading(false);
  };

  useEffect(() => { fetchQ(); }, []);

  useEffect(() => {
    const t = setTimeout(() => {
      setSearchQ(search);
      setPage(1);
      fetchQ(search, hskFilter, statusFilter, 1);
    }, 350);
    return () => clearTimeout(t);
  }, [search, hskFilter, statusFilter]);

  const handleAction = async (id: string, action: "approve" | "reject") => {
    await fetch(`/api/admin/ai-questions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, ids: [id] }),
    });
    setPreview(null);
    fetchQ(searchQ, hskFilter, statusFilter, page);
  };

  const handleBulkAction = async (action: "approve" | "reject") => {
    if (selected.size === 0) return;
    await fetch(`/api/admin/ai-questions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, ids: Array.from(selected) }),
    });
    setSelected(new Set());
    fetchQ(searchQ, hskFilter, statusFilter, page);
  };

  const toggleSelect = (id: string) => {
    setSelected(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (selected.size === questions.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(questions.map(q => q.id)));
    }
  };

  const pendingCount = stats.find(s => s.status === "pending")?.count ?? 0;

  return (
    <div className="p-4 md:p-6">
      {/* Preview Modal */}
      {preview && (
        <QuestionModal
          q={preview}
          onClose={() => setPreview(null)}
          onAction={handleAction}
        />
      )}

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-6">
        <div>
          <p className="text-xs font-bold text-purple-600 uppercase tracking-wider mb-1">✨ AI Generated</p>
          <h1 className="text-3xl font-extrabold text-on-surface">AI Câu hỏi Quiz</h1>
          <p className="text-sm text-on-surface-variant mt-1">
            Quản lý câu hỏi do AI tạo cho từng từ vựng. Mỗi câu hỏi gắn với 1 từ vựng cụ thể.
          </p>
        </div>
        <div className="flex gap-3 items-center">
          {/* Stats chips */}
          <div className="hidden sm:flex items-center gap-2 mr-2">
            <span className="text-xs bg-amber-100 text-amber-700 font-bold px-3 py-1.5 rounded-full">
              ⏳ {pendingCount} chờ duyệt
            </span>
          </div>
          {selected.size > 0 && (
            <div className="flex gap-2">
              <button onClick={() => handleBulkAction("approve")}
                className="flex items-center gap-1.5 bg-green-600 text-white px-4 py-2 rounded-xl text-sm font-bold hover:brightness-110">
                <span className="material-symbols-outlined" style={{ fontSize: 16 }}>check</span>
                Duyệt ({selected.size})
              </button>
              <button onClick={() => handleBulkAction("reject")}
                className="flex items-center gap-1.5 border border-red-200 text-red-600 px-4 py-2 rounded-xl text-sm font-bold hover:bg-red-50">
                <span className="material-symbols-outlined" style={{ fontSize: 16 }}>close</span>
                Từ chối ({selected.size})
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Search + Filters */}
      <div className="flex flex-col md:flex-row gap-3 mb-5">
        <div className="flex items-center gap-2 flex-1 border border-outline-variant/30 rounded-xl px-3 py-2.5 bg-surface-container-lowest focus-within:border-primary transition-colors">
          <span className="material-symbols-outlined text-on-surface-variant" style={{ fontSize: 18 }}>search</span>
          <input value={search} onChange={e => setSearch(e.target.value)}
            placeholder="Tìm theo chữ Hán, pinyin, nghĩa..."
            className="flex-1 text-sm outline-none bg-transparent text-on-surface" />
        </div>
        <select value={hskFilter} onChange={e => { setHskFilter(e.target.value); setPage(1); fetchQ(searchQ, e.target.value, statusFilter, 1); }}
          className="border border-outline-variant/30 rounded-xl px-4 py-2.5 text-sm bg-surface-container-lowest outline-none">
          <option value="">HSK (Tất cả)</option>
          {[1,2,3,4,5,6].map(l => <option key={l} value={l}>HSK {l}</option>)}
        </select>
        <select value={statusFilter} onChange={e => { setStatusFilter(e.target.value); setPage(1); fetchQ(searchQ, hskFilter, e.target.value, 1); }}
          className="border border-outline-variant/30 rounded-xl px-4 py-2.5 text-sm bg-surface-container-lowest outline-none">
          <option value="">Trạng thái (Tất cả)</option>
          <option value="pending">⏳ Chờ duyệt</option>
          <option value="approved">✅ Đã duyệt</option>
          <option value="rejected">❌ Từ chối</option>
        </select>
      </div>

      {/* Table */}
      <div className="bg-surface-container-lowest rounded-2xl border border-outline-variant/20 overflow-x-auto mb-6">
        <table className="w-full min-w-[700px]">
          <thead>
            <tr className="border-b border-outline-variant/10 bg-surface-container">
              <th className="px-4 py-3 text-left">
                <input type="checkbox" checked={selected.size === questions.length && questions.length > 0}
                  onChange={toggleAll}
                  className="w-4 h-4 rounded accent-primary" />
              </th>
              {["Từ vựng", "Hình", "Câu hỏi", "Đáp án đúng", "Level", "Trạng thái", "Hành động"].map(h => (
                <th key={h} className="px-4 py-3 text-left text-xs font-bold text-on-surface-variant uppercase tracking-wider">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading && [1,2,3,4,5].map(i => (
              <tr key={i} className="border-b border-outline-variant/10">
                {[1,2,3,4,5,6].map(j => <td key={j} className="px-4 py-4"><Skeleton className="h-5 w-full" /></td>)}
              </tr>
            ))}

            {!loading && questions.map(q => (
              <tr key={q.id} className={`border-b border-outline-variant/10 hover:bg-surface-container/40 transition-colors ${selected.has(q.id) ? "bg-primary/5" : ""}`}>
                <td className="px-4 py-4">
                  <input type="checkbox" checked={selected.has(q.id)} onChange={() => toggleSelect(q.id)}
                    className="w-4 h-4 rounded accent-primary" />
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center gap-2">
                    <span className="text-xl chinese-text">{q.vocabulary.hanzi}</span>
                    <div>
                      <div className="text-xs text-on-surface-variant">{q.vocabulary.pinyin}</div>
                      <div className="text-xs text-on-surface">{q.vocabulary.meaningVi}</div>
                    </div>
                  </div>
                </td>
                <td className="px-4 py-4">
                  {q.imageUrl ? (
                    <img
                      src={q.imageUrl}
                      alt="img"
                      className="w-12 h-12 rounded-lg object-cover border border-outline-variant/20 cursor-pointer hover:opacity-80 transition-opacity"
                      onClick={() => q.imageUrl && window.open(q.imageUrl, "_blank")}
                      onError={e => { (e.target as HTMLImageElement).style.display = "none"; }}
                    />
                  ) : (
                    <span className="material-symbols-outlined text-on-surface-variant/30" style={{ fontSize: 20 }}>image_not_supported</span>
                  )}
                </td>
                <td className="px-4 py-4 max-w-xs">
                  <p className="text-xs text-on-surface line-clamp-2">{q.questionText}</p>
                </td>
                <td className="px-4 py-4">
                  <span className="text-sm font-medium text-green-700 line-clamp-1">{q.correctAnswer}</span>
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${HSK_COLORS[q.hskLevel] ?? "bg-gray-400"}`} />
                    <span className="text-sm font-semibold text-on-surface">HSK {q.hskLevel}</span>
                  </div>
                </td>
                <td className="px-4 py-4">
                  <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${STATUS_CONFIG[q.status]?.cls ?? "bg-gray-100 text-gray-600"}`}>
                    {STATUS_CONFIG[q.status]?.label ?? q.status}
                  </span>
                </td>
                <td className="px-4 py-4">
                  <div className="flex gap-1">
                    <button onClick={() => setPreview(q)}
                      className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-surface-container transition-colors"
                      title="Xem & Duyệt">
                      <span className="material-symbols-outlined text-on-surface-variant" style={{ fontSize: 16 }}>visibility</span>
                    </button>
                    {q.status !== "approved" && (
                      <button onClick={() => handleAction(q.id, "approve")}
                        className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-green-50 transition-colors"
                        title="Duyệt nhanh">
                        <span className="material-symbols-outlined text-green-600" style={{ fontSize: 16 }}>check</span>
                      </button>
                    )}
                    <button onClick={() => {
                      fetch(`/api/admin/ai-questions/${q.id}`, { method: "DELETE" });
                      fetchQ(searchQ, hskFilter, statusFilter, page);
                    }}
                      className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-error/10 transition-colors"
                      title="Xoá">
                      <span className="material-symbols-outlined text-error" style={{ fontSize: 16 }}>delete</span>
                    </button>
                  </div>
                </td>
              </tr>
            ))}

            {!loading && questions.length === 0 && (
              <tr>
                <td colSpan={7} className="text-center py-14">
                  <span className="text-4xl mb-3 block">🤖</span>
                  <p className="text-sm text-on-surface-variant">Chưa có câu hỏi AI nào. Vào trang Từ vựng để tạo câu hỏi.</p>
                </td>
              </tr>
            )}
          </tbody>
        </table>

        {/* Pagination */}
        {!loading && total > 0 && (
          <div className="px-5 py-3 border-t border-outline-variant/10 flex items-center justify-between">
            <p className="text-xs text-on-surface-variant">
              Hiển thị <strong>{Math.min((page-1)*20+1, total)}–{Math.min(page*20, total)}</strong> / <strong>{total}</strong> câu hỏi
            </p>
            <div className="flex gap-1">
              <button onClick={() => { setPage(p => Math.max(1, p-1)); fetchQ(searchQ, hskFilter, statusFilter, page-1); }} disabled={page === 1}
                className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-surface-container disabled:opacity-30">
                <span className="material-symbols-outlined" style={{ fontSize: 16 }}>chevron_left</span>
              </button>
              {Array.from({ length: Math.min(5, Math.ceil(total/20)) }, (_, i) => {
                const p = Math.max(1, Math.min(Math.ceil(total/20)-4, page-2)) + i;
                return (
                  <button key={p} onClick={() => { setPage(p); fetchQ(searchQ, hskFilter, statusFilter, p); }}
                    className={`w-8 h-8 flex items-center justify-center rounded-lg text-sm font-semibold transition-colors ${p === page ? "bg-primary text-on-primary" : "hover:bg-surface-container text-on-surface"}`}>
                    {p}
                  </button>
                );
              })}
              <button onClick={() => { setPage(p => p+1); fetchQ(searchQ, hskFilter, statusFilter, page+1); }}
                disabled={page >= Math.ceil(total/20)}
                className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-surface-container disabled:opacity-30">
                <span className="material-symbols-outlined" style={{ fontSize: 16 }}>chevron_right</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
